# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestApp1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestApp1
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'



  target 'TestApp1-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNSound', :path => '../node_modules/react-native-sound'

  end

  target 'TestApp1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TestApp1-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestApp1-tvOS


end
